/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>

/* Header for class example_dokemonster_SimpleLED */

#ifndef _Included_example_dokemonster_SimpleLED
#define _Included_example_dokemonster_SimpleLED
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_dokemonster_SimpleLED
 * Method:    simpleLEDControl
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_example_dokemonster_SimpleLED_simpleLEDControl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
