/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
/* Header for class example_dokemonster_DotMatrix */

#ifndef _Included_example_dokemonster_DotMatrix
#define _Included_example_dokemonster_DotMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_dokemonster_DotMatrix
 * Method:    DotMatrixControl
 * Signature: ()Z
 */
JNIEXPORT jint JNICALL Java_example_dokemonster_DotMatrix_DotMatrixControl(JNIEnv *env, jobject thiz, jstring data);

}
#endif