/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>

/* Header for class example_dokemonster_FullLED */

#ifndef _Included_example_dokemonster_FullLED
#define _Included_example_dokemonster_FullLED

#include <string.h>
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <termios.h>
#include <sys/mman.h>
#include <errno.h>

#define FULL_LED1 9
#define FULL_LED2 8
#define FULL_LED3 7
#define FULL_LED4 6
#define ALL_LED   5

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_dokemonster_FullLED
 * Method:    fullLEDControl
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_example_dokemonster_FullLED_fullLEDControl
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
